### ISSUE TITLE
Future development of go-money

### ISSUE THREAD

**Issue by llonchj** [Rhymond/go-money#27]
Hi @Rhymond,

I was wondering how do you envision the future of go-money in terms of:

* Integration with existing `golang.org/x/text/currency`
* Complete currency list support (fiat, crypto, commodities).
* Supporting exchange rates from an external service

Thanks!

**Comment by Rhymond** [comment]
Hi @llonchj,

Sorry for late response.

I had and have plans to implement official `Go` currency library, but as you can see it's very unstable right now. I'm contstanly checking if there is some news related, but till now nothing is moving.

For us is difficult to chase all currencies (fiat, crypto, commodities etc.) and in my opinion the best way is to let application include need currencies by using `AddCurrency` method.

Where is no plans for integrating any external service into `go-money`, because `go-money` was created mainly to be new **type**, BUT there is a plans to create currency exchange library **using**  `go-money`.

Thanks you!

**Comment by llonchj** [comment]
Thanks @Rhymond,

I totally understand the difficulty of tracking all currencies and agree with the AddCurrency method.

What is your view in the currency exchange implementation? I have implemented aside `Pair(Base, Quote)` in a private repo.

Thanks!

**Comment by Rhymond** [comment]
@llonchj sounds interesting, I can't find your implementation. Could you please describe how you want to implement it?

**Comment by Rhymond** [comment]
Closing, because of inactivity
